# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contractor Companion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contractor Companion

  target 'Contractor CompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Contractor CompanionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'RAMAnimatedTabBarController'

pod 'FoldingCell'

pod 'SwiftEntryKit'

end